# docker-compose.deploy.yml
version: '3.8'

volumes:
  userdb_vol:
  productdb_vol:
  orderdb_vol:

networks:
  micro_network:
    external:
      name: micro_network

services:
  user-api:
    container_name: cuser-service
    build:
      context: ../User
    ports:
    - "5001:5001"
    depends_on:
      - user-db
    networks:
      - micro_network
    restart: always

  user-db:
    container_name: cuser_dbase
    image: mysql:8
    ports:
    - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: danops_dc_2022
      MYSQL_DATABASE: user
      MYSQL_USER: danops
      MYSQL_PASSWORD: danops_2022
    networks:
      - micro_network
    volumes:
    - userdb_vol:/var/lib/mysql

  product-api:
    container_name: cproduct-service
    build:
      context: ../Product
    ports:
    - "5002:5002"
    depends_on:
      - product-db
    networks:
      - micro_network
    restart: always

  product-db:
    container_name: cproduct_dbase
    image: mysql:8
    ports:
    - "32001:3306"
    environment:
      MYSQL_ROOT_PASSWORD: danops_dc_2022
      MYSQL_DATABASE: product
      MYSQL_USER: danops
      MYSQL_PASSWORD: danops_2022
    networks:
      - micro_network
    volumes:
    - productdb_vol:/var/lib/mysql

  order-api:
    container_name: corder-service
    build:
      context: ../Order
    ports:
    - "5003:5003"
    depends_on:
      - order-db
    networks:
      - micro_network
    restart: always

  order-db:
    container_name: corder_dbase
    image: mysql:8
    ports:
    - "32002:3306"
    environment:
      MYSQL_ROOT_PASSWORD: danops_dc_2022
      MYSQL_DATABASE: order
      MYSQL_USER: danops
      MYSQL_PASSWORD: danops_2022
    networks:
      - micro_network
    volumes:
    - orderdb_vol:/var/lib/mysql

  frontend-app:
    container_name: cfrontend-app
    build:
      context: .
    ports:
    - "5000:5000"
    networks:
      - micro_network
    restart: always